# Generated by Django 4.1.1 on 2022-10-19 17:54

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='photos.photo'),
        ),
    ]
